version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/html
      - ./requirements/nginx/conf:/etc/nginx/conf.d
    networks:
      - inception_network
    depends_on:
      - wordpress
    restart: unless-stopped
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_user
      - db_password

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - inception_network
    restart: unless-stopped
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_user
      - db_password

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress_volume:/var/www/wordpress
    networks:
      - inception_network
    restart: unless-stopped
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_user
      - db_password
      - wp_admin_user
      - wp_admin_password
      - wp_user
      - wp_user_password

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/mokariou/data/mariadb
      o: bind
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/mokariou/data/wordpress
      o: bind

networks:
  inception_network:
    driver: bridge

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
  wp_admin_user:
    file: ./secrets/wp_admin_user.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt
  wp_user:
    file: ./secrets/wp_user.txt
  wp_user_password:
    file: ./secrets/wp_user_password.txt