version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/wordpress
      - ./requirements/nginx/conf:/etc/nginx/conf.d
    networks:
      - inception_network
    depends_on:
      - wordpress
    restart: unless-stopped
    env_file:
      - .env

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - inception_network
    restart: unless-stopped
    env_file:
      - .env

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress_volume:/var/www/wordpress
    networks:
      - inception_network
    restart: unless-stopped
    env_file:
      - .env

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/mokariou/data/mariadb
      o: bind
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/mokariou/data/wordpress
      o: bind

networks:
  inception_network:
    driver: bridge

